name: UDS CI

on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: 'Tag and release version (e.g. v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      release_version: ${{ github.event.inputs.RELEASE_VERSION }}
      jar_path: ${{ steps.build.outputs.jar_path }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        id: build
        run: |
          mvn -B package --file ./pom.xml
          echo "jar_path=./target/udsapp.jar" >> $GITHUB_OUTPUT

      - name: Upload jar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: ${{ steps.build.outputs.jar_path }}

  tag:
    needs: build
    runs-on: ubuntu-latest

    outputs:
      release_version: ${{ needs.build.outputs.release_version }}

    env:
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for tags
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create Git Tag
        run: |
          git tag ${{ needs.build.outputs.release_version }}
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }} ${{ needs.build.outputs.release_version }}

  release:
    needs: tag
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download built jar
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Upload Release to GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.tag.outputs.release_version }}
          name: Release ${{ needs.tag.outputs.release_version }}
          files: udsapp.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
